<a href="https://colab.research.google.com/github/nikdrako/Machine-learning-projects/blob/main/homework_mykola_sysiuk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [ ]:
arr = np.genfromtxt(url, dtype = float , delimiter = ',', usecols= (0,1,2,3))

Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)

In [ ]:
arr = arr.tolist()

In [ ]:
print(type(arr))

<class 'list'>


In [ ]:
arr = np.array(arr)

In [ ]:
print(arr.ndim)
print(type(arr))
arr.dtype

2
<class 'numpy.ndarray'>


dtype('float64')

Порахувати mean, median, standard deviation для 1-ї колонки

In [ ]:
mean = np.mean(arr[:, 0])

In [ ]:
print(mean)

5.843333333333334


In [ ]:
arr_med = np.median(arr[:,0])

In [ ]:
arr_med

5.8

In [ ]:
arr_std = np.std(arr[:,0])
arr_std

0.8253012917851409

Вставити 20 значень np.nan на випадкові позиції в масиві (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)

In [ ]:
arr[np.unravel_index(np.random.choice(arr.size, 20, replace=False), arr.shape)] = np.nan

Знайти позиції вставлених значень np.nan в 1-й колонці

In [ ]:
indx = np.where(np.isnan(arr[:,0]))
indx

(array([  1,   2,  27,  29,  46, 119, 145]),)

Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)

In [ ]:
filt_arr = arr[(arr[:, 2] > 1.5) & (arr[:, 0] < 5.0)]
filt_arr

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

Замінити всі значення np.nan на 0


In [ ]:
arr[np.isnan(arr)] = 0


Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю

In [ ]:
unique_val, count = np.unique(arr, return_counts=True)
print(unique_val)
print(count)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.
 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8
 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6
 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4
 7.6 7.7 7.9]
[20  6 28  7  7  1  1  8  3  7 19 20 25 11  5 12  6  7  6  6 12  6 10  5
  9 14  9 27 12 13  8 12  7  3  3  7  5  6  4  5  3  8  9  6  5  9 10 14
 15  5  3  8 10 12 11 10  5  7  9  4 10  8  5  2  9  3  5  1  1  3  1  1
  1  4  1]


Розбити масив по вертикалі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)

In [ ]:
arr_split = np.split(arr, 2)
print(arr_split)

[array([[5.1, 0. , 1.4, 0.2],
       [0. , 3. , 1.4, 0.2],
       [0. , 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 0. , 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 0. , 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 0. , 0.4],
       [4.6, 0. , 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 0. , 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [0. , 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [0. , 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 

Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням

In [ ]:
arr1, arr2 = np.split(arr, 2)
sorted_arr1 = arr1[arr1[:, 0].argsort()]
sorted_arr2 = arr2[arr2[:, 0].argsort()[::-1]]
print(sorted_arr1,sorted_arr2)

[[0.  3.8 1.6 0.2]
 [0.  3.2 1.6 0.2]
 [0.  3.5 1.5 0.2]
 [0.  3.  1.4 0.2]
 [0.  3.2 1.3 0.2]
 [4.3 3.  1.1 0.1]
 [4.4 3.  1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 0.  1.  0.2]
 [4.6 3.2 1.4 0.2]
 [4.8 3.1 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [4.8 3.4 0.  0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.  3.3 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.  3.4 1.5 0.2]
 [5.  2.  3.5 1. ]
 [5.  3.6 1.4 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.1 0.  1.4 0.2]
 [5.1 3.5 1.4 0.3]
 [5.1 3.8 1.5 0.3]
 [5.1 3.7 0.  0.4]
 [5.1 3.3 1.7 0.5]
 [5.2 2.7 3.9 1.4]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.4 3.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.9 0.  0.4]
 [5.4 3.9 1.7 0.4]
 [5.4 0.  1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [5.5 2.3 4.  1.3]
 [5.5 4.2 1.4 0.2]
 [5.6 2.9 3.6 1.3]
 [5.6 3.  4.

Зібрати обидва массиви в одне ціле

In [ ]:
np.concatenate([arr1, arr2], axis=0)

array([[5.1, 0. , 1.4, 0.2],
       [0. , 3. , 1.4, 0.2],
       [0. , 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 0. , 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 0. , 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 0. , 0.4],
       [4.6, 0. , 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 0. , 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [0. , 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [0. , 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

Знайти найбільш часто повторюване значення в массиві

In [ ]:
unique_val, count = np.unique(arr, return_counts=True)
print(unique_val, count)
print("//////////////////////////")
print(unique_val[np.argmax(count)])

[0.  0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.
 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8
 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6
 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4
 7.6 7.7 7.9] [20  6 28  7  7  1  1  8  3  7 19 20 25 11  5 12  6  7  6  6 12  6 10  5
  9 14  9 27 12 13  8 12  7  3  3  7  5  6  4  5  3  8  9  6  5  9 10 14
 15  5  3  8 10 12 11 10  5  7  9  4 10  8  5  2  9  3  5  1  1  3  1  1
  1  4  1]
//////////////////////////
0.2


Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.

In [ ]:
def multiplication(arr):
  means = np.mean(arr)
  return np.where(arr < means, arr*2 ,arr/4)

Застосувати отриману функцію до 3-ї колонки

In [ ]:
multiplication(arr[:,0])

array([10.2  ,  0.   ,  0.   ,  9.2  , 10.   , 10.8  ,  9.2  , 10.   ,
        8.8  ,  9.8  , 10.8  ,  9.6  ,  9.6  ,  8.6  ,  1.45 ,  1.425,
       10.8  , 10.2  ,  1.425, 10.2  , 10.8  , 10.2  ,  9.2  , 10.2  ,
        9.6  , 10.   , 10.   ,  0.   , 10.4  ,  0.   ,  9.6  , 10.8  ,
       10.4  , 11.   ,  9.8  , 10.   , 11.   ,  9.8  ,  8.8  , 10.2  ,
       10.   ,  9.   ,  8.8  , 10.   , 10.2  ,  9.6  ,  0.   ,  9.2  ,
       10.6  , 10.   ,  1.75 ,  1.6  ,  1.725, 11.   ,  1.625,  1.425,
        1.575,  9.8  ,  1.65 , 10.4  , 10.   ,  1.475,  1.5  ,  1.525,
        1.4  ,  1.675,  1.4  ,  1.45 ,  1.55 ,  1.4  ,  1.475,  1.525,
        1.575,  1.525,  1.6  ,  1.65 ,  1.7  ,  1.675,  1.5  ,  1.425,
       11.   , 11.   ,  1.45 ,  1.5  , 10.8  ,  1.5  ,  1.675,  1.575,
        1.4  , 11.   , 11.   ,  1.525,  1.45 , 10.   ,  1.4  ,  1.425,
        1.425,  1.55 , 10.2  ,  1.425,  1.575,  1.45 ,  1.775,  1.575,
        1.625,  1.9  ,  9.8  ,  1.825,  1.675,  1.8  ,  1.625,  1.6  ,
      

In [ ]:
multiplication(arr[:,1])

array([0.   , 0.75 , 0.8  , 0.775, 0.9  , 0.975, 0.85 , 0.85 , 5.8  ,
       0.775, 0.   , 0.85 , 0.75 , 0.75 , 1.   , 1.1  , 0.975, 0.875,
       0.95 , 0.95 , 0.85 , 0.925, 0.   , 0.825, 0.85 , 0.75 , 0.85 ,
       0.875, 0.85 , 0.8  , 0.775, 0.85 , 1.025, 1.05 , 0.775, 0.8  ,
       0.875, 0.775, 0.75 , 0.85 , 0.875, 4.6  , 0.8  , 0.875, 0.95 ,
       0.75 , 0.95 , 0.8  , 0.925, 0.825, 0.8  , 0.8  , 0.775, 4.6  ,
       5.6  , 5.6  , 0.825, 4.8  , 5.8  , 5.4  , 4.   , 0.75 , 4.4  ,
       5.8  , 5.8  , 0.775, 0.75 , 5.4  , 4.4  , 5.   , 0.8  , 5.6  ,
       5.   , 5.6  , 5.8  , 0.75 , 5.6  , 0.75 , 5.8  , 5.2  , 4.8  ,
       4.8  , 5.4  , 5.4  , 0.75 , 0.85 , 0.775, 4.6  , 0.75 , 5.   ,
       5.2  , 0.75 , 5.2  , 4.6  , 5.4  , 0.75 , 0.   , 5.8  , 5.   ,
       5.6  , 0.825, 5.4  , 0.75 , 5.8  , 0.75 , 0.75 , 5.   , 5.8  ,
       5.   , 0.9  , 0.8  , 5.4  , 0.75 , 5.   , 5.6  , 0.8  , 0.75 ,
       0.95 , 5.2  , 4.4  , 0.8  , 5.6  , 5.6  , 5.4  , 0.825, 0.8  ,
       5.6  , 0.75 ,

In [ ]:
multiplication(arr[:,2])

array([2.8  , 2.8  , 2.6  , 3.   , 2.8  , 3.4  , 2.8  , 3.   , 2.8  ,
       3.   , 3.   , 3.2  , 2.8  , 2.2  , 2.4  , 3.   , 0.   , 2.8  ,
       3.4  , 3.   , 3.4  , 0.   , 2.   , 3.4  , 0.   , 3.2  , 3.2  ,
       3.   , 2.8  , 3.2  , 3.2  , 3.   , 3.   , 2.8  , 3.   , 2.4  ,
       2.6  , 3.   , 2.6  , 3.   , 2.6  , 2.6  , 2.6  , 3.2  , 3.8  ,
       2.8  , 3.2  , 2.8  , 3.   , 2.8  , 1.175, 1.125, 1.225, 1.   ,
       1.15 , 1.125, 1.175, 6.6  , 0.   , 0.975, 7.   , 1.05 , 1.   ,
       1.175, 7.2  , 1.1  , 1.125, 1.025, 1.125, 0.975, 1.2  , 1.   ,
       1.225, 1.175, 1.075, 1.1  , 1.2  , 1.25 , 1.125, 7.   , 0.95 ,
       0.925, 0.975, 1.275, 1.125, 1.125, 1.175, 1.1  , 1.025, 1.   ,
       1.1  , 1.15 , 1.   , 6.6  , 1.05 , 1.05 , 1.05 , 1.075, 6.   ,
       1.025, 1.5  , 1.275, 1.475, 1.4  , 1.45 , 0.   , 1.125, 1.575,
       1.45 , 1.525, 1.275, 1.325, 1.375, 1.25 , 1.275, 1.325, 1.375,
       1.675, 1.725, 1.25 , 1.425, 1.225, 1.675, 1.225, 1.425, 1.5  ,
       1.2  , 1.225,

In [ ]:
multiplication(arr[:,3])

array([0.4  , 0.4  , 0.4  , 0.4  , 0.4  , 0.8  , 0.6  , 0.4  , 0.4  ,
       0.2  , 0.4  , 0.4  , 0.2  , 0.2  , 0.4  , 0.8  , 0.8  , 0.6  ,
       0.6  , 0.6  , 0.4  , 0.8  , 0.4  , 1.   , 0.4  , 0.4  , 0.8  ,
       0.4  , 0.4  , 0.4  , 0.4  , 0.8  , 0.2  , 0.4  , 0.2  , 0.4  ,
       0.4  , 0.2  , 0.4  , 0.4  , 0.6  , 0.6  , 0.4  , 1.2  , 0.8  ,
       0.6  , 0.4  , 0.4  , 0.4  , 0.4  , 0.35 , 0.375, 0.375, 0.325,
       0.375, 0.325, 0.4  , 2.   , 0.325, 0.35 , 2.   , 0.375, 2.   ,
       0.35 , 0.325, 0.35 , 0.375, 2.   , 0.375, 2.2  , 0.45 , 0.325,
       0.375, 0.3  , 0.325, 0.35 , 0.35 , 0.   , 0.375, 2.   , 0.   ,
       2.   , 0.3  , 0.4  , 0.375, 0.4  , 0.375, 0.325, 0.325, 0.325,
       0.3  , 0.35 , 0.3  , 2.   , 0.325, 0.3  , 0.325, 0.325, 2.2  ,
       0.325, 0.625, 0.475, 0.525, 0.45 , 0.55 , 0.525, 0.425, 0.45 ,
       0.45 , 0.625, 0.5  , 0.475, 0.525, 0.5  , 0.6  , 0.575, 0.45 ,
       0.55 , 0.575, 0.375, 0.575, 0.5  , 0.5  , 0.45 , 0.525, 0.45 ,
       0.45 , 0.45 ,